// Mock data for appointments
export const appointments = [
  {
    id: 6,
    name: "Saanvi Gupta",
    time: "10:15 AM",
    reason: "Asthma Checkup",
    type: "Follow-up",
    status: "Scheduled",
    contact: "+91 93210 98765",
    age: 12,
    gender: "Female",
    bloodGroup: "B+",
    weight: "38",
    height: "145",
    bloodPressure: "110/70",
    sugarLevel: "95",
    allergies: "Dust Mites, Pollen",
    medications: "Salbutamol Inhaler (as needed)",
    conditions: ["Asthma"],
    pastDisease: "Childhood pneumonia (5 years ago)",
    familyHistory: "Father has asthma, mother has allergies",
    notes: "Patient has been using the inhaler twice this week. Spirometry test scheduled."
  },
  {
    id: 7,
    name: "Mohan Reddy",
    time: "10:30 AM",
    reason: "Knee Pain",
    type: "New Patient",
    status: "Scheduled",
    contact: "+91 92109 87654",
    age: 62,
    gender: "Male",
    bloodGroup: "O+",
    weight: "78",
    height: "168",
    bloodPressure: "135/85",
    sugarLevel: "110",
    allergies: "None",
    medications: "Ibuprofen 400mg (as needed)",
    conditions: ["Osteoarthritis (suspected)"],
    pastDisease: "Hypertension (controlled), Type 2 Diabetes (controlled)",
    familyHistory: "Father had diabetes, mother had arthritis",
    notes: "Patient complains of persistent right knee pain, especially when climbing stairs. X-ray ordered."
  },
  {
    id: 8,
    name: "Aisha Khan",
    time: "10:45 AM",
    reason: "Skin Rash",
    type: "Consultation",
    status: "Checked-In",
    contact: "+91 91098 76543",
    age: 22,
    gender: "Female",
    bloodGroup: "A+",
    weight: "55",
    height: "162",
    bloodPressure: "115/75",
    sugarLevel: "88",
    allergies: "None",
    medications: "None",
    conditions: ["Dermatitis"],
    pastDisease: "None",
    familyHistory: "Sister has eczema",
    notes: "Sudden onset of itchy red rash on both arms. Patient denies new soaps or lotions."
  },
  {
    id: 9,
    name: "Rajesh Malhotra",
    time: "11:00 AM",
    reason: "Post-op Checkup",
    type: "Follow-up",
    status: "Scheduled",
    contact: "+91 90987 65432",
    age: 51,
    gender: "Male",
    bloodGroup: "AB+",
    weight: "82",
    height: "175",
    bloodPressure: "128/82",
    sugarLevel: "102",
    allergies: "Codeine",
    medications: "Antibiotics (Amoxicillin)",
    conditions: ["Appendectomy (1 week ago)"],
    pastDisease: "Appendicitis (1 week ago), Gallstones (3 years ago)",
    familyHistory: "Father had appendicitis at age 45",
    notes: "Incision site healing well. No signs of infection. Sutures to be removed next week."
  },
  {
    id: 10,
    name: "Isha Nair",
    time: "11:15 AM",
    reason: "Anxiety",
    type: "Consultation",
    status: "Scheduled",
    contact: "+91 89876 54321",
    age: 34,
    gender: "Female",
    bloodGroup: "B-",
    weight: "62",
    height: "158",
    bloodPressure: "120/78",
    sugarLevel: "92",
    allergies: "None",
    medications: "Sertraline 50mg",
    conditions: ["Generalized Anxiety Disorder"],
    pastDisease: "Mild depression (2 years ago)",
    familyHistory: "Mother has anxiety disorder, maternal grandmother had depression",
    notes: "Follow-up on new medication. Patient reports mild side effects but improved mood."
  },
  {
    id: 11,
    name: "Arjun Verma",
    time: "11:30 AM",
    reason: "Headache",
    type: "New Patient",
    status: "Scheduled",
    contact: "+91 88765 43210",
    age: 41,
    gender: "Male",
    bloodGroup: "A+",
    weight: "75",
    height: "172",
    bloodPressure: "130/80",
    sugarLevel: "98",
    allergies: "None",
    medications: "None",
    conditions: ["Migraine (suspected)"],
    pastDisease: "Occasional tension headaches",
    familyHistory: "Father and maternal uncle have migraines",
    notes: "Patient reports recurring, severe headaches with light sensitivity. Keeping a headache diary."
  },
  {
    id: 12,
    name: "Diya Mehta",
    time: "11:45 AM",
    reason: "Vaccination",
    type: "Routine",
    status: "Checked-In",
    contact: "+91 87654 32109",
    age: 5,
    gender: "Female",
    bloodGroup: "O+",
    weight: "18",
    height: "105",
    bloodPressure: "95/60",
    sugarLevel: "85",
    allergies: "None",
    medications: "None",
    conditions: [],
    pastDisease: "None",
    familyHistory: "No significant family history",
    notes: "Scheduled MMR vaccine (Dose 2). Patient is healthy today."
  },
  {
    id: 13,
    name: "Karan Singh",
    time: "12:00 PM",
    reason: "Abdominal Pain",
    type: "Consultation",
    status: "Scheduled",
    contact: "+91 86543 21098",
    age: 38,
    gender: "Male",
    bloodGroup: "B+",
    weight: "85",
    height: "178",
    bloodPressure: "138/88",
    sugarLevel: "105",
    allergies: "None",
    medications: "Antacids",
    conditions: ["GERD"],
    pastDisease: "Gastritis (1 year ago), Peptic ulcer (3 years ago)",
    familyHistory: "Father has GERD, paternal grandfather had stomach ulcers",
    notes: "Patient reports worsening acid reflux and abdominal pain, especially after meals."
  },
  {
    id: 14,
    name: "Myra Deshpande",
    time: "12:15 PM",
    reason: "Thyroid Test",
    type: "Follow-up",
    status: "Scheduled",
    contact: "+91 85432 10987",
    age: 29,
    gender: "Female",
    bloodGroup: "A+",
    weight: "68",
    height: "165",
    bloodPressure: "118/76",
    sugarLevel: "94",
    allergies: "None",
    medications: "Levothyroxine 50mcg",
    conditions: ["Hypothyroidism"],
    pastDisease: "Hyperthyroidism (diagnosed 2 years ago, now hypothyroid post-treatment)",
    familyHistory: "Mother and maternal aunt have hypothyroidism",
    notes: "Reviewing recent TSH lab results. Adjusting medication dosage."
  },
  {
    id: 15,
    name: "Sameer Ali",
    time: "12:30 PM",
    reason: "Annual Physical",
    type: "Routine",
    status: "Checked-In",
    contact: "+91 84321 09876",
    age: 47,
    gender: "Male",
    bloodGroup: "O+",
    weight: "88",
    height: "170",
    bloodPressure: "140/90",
    sugarLevel: "115",
    allergies: "None",
    medications: "Atorvastatin 20mg",
    conditions: ["High Cholesterol"],
    pastDisease: "Hyperlipidemia (5 years), Pre-diabetes (1 year)",
    familyHistory: "Father had heart attack at age 55, mother has high cholesterol",
    notes: "Routine annual checkup. Full blood panel ordered. Discussed diet and exercise."
  }
]

